-- REV UP Contest: Signs Scoring
-- Signs = New signed accounts (CONTRACT_SIGNED_DATE in contest window)
-- Services/Retail = 3 pts, F&B = 1 pt
-- Source: SMB_CONTRACT_OPPORTUNITIES joined to VDIM_USER for business category

CREATE OR REPLACE VIEW APP_SALES.APP_SALES_ETL.VW_REVUP_SIGNS AS
SELECT 
    o.OPPORTUNITY_ID,
    o.FULL_NAME AS REP_NAME,
    o.LDAP AS REP_LDAP,
    o.MANAGER,
    f.REGION,
    o.CONTRACT_SIGNED_DATE AS SIGN_DATE,
    o.OPPORTUNITY_AMOUNT_LOCAL AS OPPORTUNITY_AMOUNT,
    u.BUSINESS_CATEGORY,
    CASE 
        WHEN u.BUSINESS_CATEGORY = 'food_and_drink' THEN 'F&B'
        ELSE 'Services/Retail'
    END AS CONTEST_VERTICAL,
    CASE 
        WHEN u.BUSINESS_CATEGORY = 'food_and_drink' THEN 1
        ELSE 3
    END AS BASE_POINTS,
    o.MERCHANT_TOKEN
FROM APP_SALES.APP_SALES_ETL.SMB_CONTRACT_OPPORTUNITIES o
JOIN APP_BI.HEXAGON.VDIM_USER u 
    ON o.MERCHANT_TOKEN = u.USER_TOKEN
JOIN APP_SALES.APP_SALES_ETL.FACT_FIELD_SALES_EMPLOYMENT_CURRENT f 
    ON o.LDAP = f.LDAP 
    AND f.IS_SALES_REP = TRUE
WHERE o.TEAM = 'Sales - US Field'
    AND o.CONTRACT_SIGNED_DATE >= '2026-07-01'
    AND o.CONTRACT_SIGNED_DATE < '2026-08-02';
