-- REV UP Contest: Activations Scoring
-- Activations = Live and processing (from ACTIVATION_CREDIT_VIEW)
-- Services/Retail = 3 pts, F&B = 1 pt
-- Source: ACTIVATION_CREDIT_VIEW joined to VDIM_USER for business category

CREATE OR REPLACE VIEW APP_SALES.APP_SALES_ETL.VW_REVUP_ACTIVATIONS AS
SELECT 
    a.OPPORTUNITY_ID,
    a.ACTIVATION_OWNER_NAME AS REP_NAME,
    a.ACTIVATION_OWNER_LDAP AS REP_LDAP,
    a.ACTIVATION_MANAGER AS MANAGER,
    f.REGION,
    a.ACTIVATION_DATE,
    u.BUSINESS_CATEGORY,
    CASE 
        WHEN u.BUSINESS_CATEGORY = 'food_and_drink' THEN 'F&B'
        ELSE 'Services/Retail'
    END AS CONTEST_VERTICAL,
    CASE 
        WHEN u.BUSINESS_CATEGORY = 'food_and_drink' THEN 1
        ELSE 3
    END AS BASE_POINTS,
    a.MERCHANT_TOKEN
FROM APP_SALES.APP_SALES_ETL.ACTIVATION_CREDIT_VIEW a
JOIN APP_BI.HEXAGON.VDIM_USER u 
    ON a.MERCHANT_TOKEN = u.USER_TOKEN
JOIN APP_SALES.APP_SALES_ETL.FACT_FIELD_SALES_EMPLOYMENT_CURRENT f 
    ON a.ACTIVATION_OWNER_LDAP = f.LDAP 
    AND f.IS_SALES_REP = TRUE
WHERE a.ACTIVATION_OWNER_SALES_TEAM = 'Sales - US Field'
    AND a.ACTIVATION_DATE >= '2026-07-01'
    AND a.ACTIVATION_DATE < '2026-08-02';
