-- REV UP Contest: Double Points Bonus
-- SIGNED + ACTIVATED in July (250k min opportunity amount) = DOUBLE POINTS on both sign and activation
-- All verticals eligible for double points

CREATE OR REPLACE VIEW APP_SALES.APP_SALES_ETL.VW_REVUP_DOUBLE_POINTS AS
SELECT 
    s.OPPORTUNITY_ID,
    s.REP_NAME,
    s.REP_LDAP,
    s.MANAGER,
    s.REGION,
    s.SIGN_DATE,
    a.ACTIVATION_DATE,
    s.OPPORTUNITY_AMOUNT,
    s.CONTEST_VERTICAL,
    s.BASE_POINTS AS SIGN_BASE_POINTS,
    a.BASE_POINTS AS ACTIVATION_BASE_POINTS,
    -- Double points applies to BOTH the sign and activation points
    s.BASE_POINTS AS SIGN_BONUS_POINTS,
    a.BASE_POINTS AS ACTIVATION_BONUS_POINTS,
    (s.BASE_POINTS + a.BASE_POINTS) AS TOTAL_BONUS_POINTS
FROM APP_SALES.APP_SALES_ETL.VW_REVUP_SIGNS s
JOIN APP_SALES.APP_SALES_ETL.VW_REVUP_ACTIVATIONS a
    ON s.MERCHANT_TOKEN = a.MERCHANT_TOKEN
    AND s.REP_LDAP = a.REP_LDAP
WHERE s.OPPORTUNITY_AMOUNT >= 250000
    AND s.SIGN_DATE >= '2026-07-01'
    AND s.SIGN_DATE < '2026-08-01'
    AND a.ACTIVATION_DATE >= '2026-07-01'
    AND a.ACTIVATION_DATE < '2026-08-01';
