-- REV UP Contest: Square Loans Scoring
-- All verticals eligible
-- Above $75k = 9 pts, Up to $75k = 6 pts, Up to $25k = 3 pts
-- Source: PLAN_GROUPS joined via VDIM_USER to SMB_CONTRACT_OPPORTUNITIES for rep attribution

CREATE OR REPLACE VIEW APP_SALES.APP_SALES_ETL.VW_REVUP_LOANS AS
SELECT 
    pg.PLAN_GROUP_ID,
    f.FULL_NAME AS REP_NAME,
    f.LDAP AS REP_LDAP,
    f.DIRECT_LEAD AS MANAGER,
    f.REGION,
    pg.ACTIVATED_AT::DATE AS LOAN_DATE,
    pg.FINANCED_CENTS / 100 AS LOAN_AMOUNT_USD,
    pg.PRODUCT_NAME,
    CASE 
        WHEN pg.FINANCED_CENTS / 100 > 75000 THEN 9
        WHEN pg.FINANCED_CENTS / 100 > 25000 THEN 6
        ELSE 3
    END AS POINTS,
    CASE 
        WHEN pg.FINANCED_CENTS / 100 > 75000 THEN 'Above $75k'
        WHEN pg.FINANCED_CENTS / 100 > 25000 THEN 'Up to $75k'
        ELSE 'Up to $25k'
    END AS LOAN_TIER
FROM APP_CAPITAL.APP_CAPITAL.PLAN_GROUPS pg
JOIN APP_BI.HEXAGON.VDIM_USER u 
    ON pg.PRIMARY_USER_TOKEN = u.USER_TOKEN
JOIN APP_SALES.APP_SALES_ETL.SMB_CONTRACT_OPPORTUNITIES o 
    ON u.MERCHANT_TOKEN = o.MERCHANT_TOKEN
JOIN APP_SALES.APP_SALES_ETL.FACT_FIELD_SALES_EMPLOYMENT_CURRENT f 
    ON o.LDAP = f.LDAP 
    AND f.IS_SALES_REP = TRUE
WHERE pg.ACTIVATED_AT >= '2026-07-01'
    AND pg.ACTIVATED_AT < '2026-08-02'
    AND pg.STATUS NOT IN ('canceled', 'declined')
    AND pg.CURRENCY_CODE = 'USD'
    AND o.TEAM = 'Sales - US Field';
