-- REV UP Contest: Regional Standings
-- East vs. West vs. Central
-- Prize: Trophy + Pride for the winning region

CREATE OR REPLACE VIEW APP_SALES.APP_SALES_ETL.VW_REVUP_REGIONAL_STANDINGS AS
SELECT 
    REGION,
    COUNT(DISTINCT REP_LDAP) AS REP_COUNT,
    SUM(SIGN_POINTS) AS TOTAL_SIGN_POINTS,
    SUM(SIGN_COUNT) AS TOTAL_SIGNS,
    SUM(ACTIVATION_POINTS) AS TOTAL_ACTIVATION_POINTS,
    SUM(ACTIVATION_COUNT) AS TOTAL_ACTIVATIONS,
    SUM(DOUBLE_BONUS_POINTS) AS TOTAL_DOUBLE_BONUS_POINTS,
    SUM(LOAN_POINTS) AS TOTAL_LOAN_POINTS,
    SUM(LOAN_COUNT) AS TOTAL_LOANS,
    SUM(TOTAL_POINTS) AS TOTAL_POINTS,
    -- Points per rep (normalized for fair comparison)
    ROUND(SUM(TOTAL_POINTS) / NULLIF(COUNT(DISTINCT REP_LDAP), 0), 2) AS POINTS_PER_REP
FROM APP_SALES.APP_SALES_ETL.VW_REVUP_LEADERBOARD
WHERE REGION IS NOT NULL
GROUP BY REGION
ORDER BY TOTAL_POINTS DESC;
