-- REV UP Q3 Fast Start - Full Leaderboard Query (CORRECTED)
-- Fixes: 
--   1. VDIM_USER dedup uses F&B priority (not alphabetical sort)
--   2. Proper QUALIFY ROW_NUMBER() to eliminate join inflation
--   3. Region assignment via DIRECT_LEAD manager mapping
-- Last validated: 2026-07-10
-- Fix: LEFT JOIN to VDIM_USER so merchants missing from that table still count (default to non-F&B = 3 pts)

WITH signs AS (
  SELECT
    o.OPPORTUNITY_ID,
    o.LDAP AS REP_LDAP,
    o.FULL_NAME AS REP_NAME,
    o.MERCHANT_TOKEN,
    o.OPPORTUNITY_AMOUNT_LOCAL,
    o.CONTRACT_SIGNED_DATE,
    CASE WHEN u.BUSINESS_CATEGORY = 'food_and_drink' THEN 1 ELSE 0 END AS IS_FNB
  FROM APP_SALES.APP_SALES_ETL.SMB_CONTRACT_OPPORTUNITIES o
  LEFT JOIN APP_BI.HEXAGON.VDIM_USER u ON o.MERCHANT_TOKEN = u.MERCHANT_TOKEN
  JOIN APP_SALES.APP_SALES_ETL.FACT_FIELD_SALES_EMPLOYMENT_CURRENT e ON o.LDAP = e.LDAP
  WHERE o.CONTRACT_SIGNED_DATE >= '2026-07-01'
    AND o.CONTRACT_SIGNED_DATE < '2026-08-02'
    AND e.SALES_TEAM = 'Sales - US Field'
    AND e.ACTIVE_STATUS = 'Active'
  QUALIFY ROW_NUMBER() OVER (PARTITION BY o.OPPORTUNITY_ID ORDER BY CASE WHEN u.BUSINESS_CATEGORY = 'food_and_drink' THEN 0 ELSE 1 END) = 1
),
activations AS (
  SELECT
    a.OPPORTUNITY_ID,
    a.ACTIVATION_OWNER_LDAP AS REP_LDAP,
    a.ACTIVATION_OWNER_NAME AS REP_NAME,
    a.MERCHANT_TOKEN,
    a.ACTIVATION_DATE,
    CASE WHEN u.BUSINESS_CATEGORY = 'food_and_drink' THEN 1 ELSE 0 END AS IS_FNB
  FROM APP_SALES.APP_SALES_ETL.ACTIVATION_CREDIT_VIEW a
  LEFT JOIN APP_BI.HEXAGON.VDIM_USER u ON a.MERCHANT_TOKEN = u.MERCHANT_TOKEN
  JOIN APP_SALES.APP_SALES_ETL.FACT_FIELD_SALES_EMPLOYMENT_CURRENT e ON a.ACTIVATION_OWNER_LDAP = e.LDAP
  WHERE a.ACTIVATION_DATE >= '2026-07-01'
    AND a.ACTIVATION_DATE < '2026-08-02'
    AND e.SALES_TEAM = 'Sales - US Field'
    AND e.ACTIVE_STATUS = 'Active'
  QUALIFY ROW_NUMBER() OVER (PARTITION BY a.OPPORTUNITY_ID ORDER BY CASE WHEN u.BUSINESS_CATEGORY = 'food_and_drink' THEN 0 ELSE 1 END) = 1
),
loans AS (
  SELECT
    pg.PLAN_GROUP_ID,
    o.LDAP AS REP_LDAP,
    o.FULL_NAME AS REP_NAME,
    pg.FINANCED_CENTS / 100.0 AS LOAN_AMOUNT,
    pg.ACTIVATED_AT::DATE AS LOAN_DATE,
    CASE 
      WHEN pg.FINANCED_CENTS / 100.0 > 75000 THEN 9
      WHEN pg.FINANCED_CENTS / 100.0 > 25000 THEN 6
      ELSE 3
    END AS LOAN_POINTS
  FROM APP_CAPITAL.APP_CAPITAL.PLAN_GROUPS pg
  JOIN APP_BI.HEXAGON.VDIM_USER u ON pg.PRIMARY_USER_TOKEN = u.USER_TOKEN
  JOIN APP_SALES.APP_SALES_ETL.SMB_CONTRACT_OPPORTUNITIES o ON u.MERCHANT_TOKEN = o.MERCHANT_TOKEN
  JOIN APP_SALES.APP_SALES_ETL.FACT_FIELD_SALES_EMPLOYMENT_CURRENT e ON o.LDAP = e.LDAP
  WHERE pg.ACTIVATED_AT >= '2026-07-01'
    AND pg.ACTIVATED_AT < '2026-08-02'
    AND pg.STATUS NOT IN ('canceled', 'declined')
    AND pg.CURRENCY_CODE = 'USD'
    AND e.SALES_TEAM = 'Sales - US Field'
    AND e.ACTIVE_STATUS = 'Active'
  QUALIFY ROW_NUMBER() OVER (PARTITION BY pg.PLAN_GROUP_ID, o.LDAP ORDER BY pg.ACTIVATED_AT) = 1
),
double_bonus AS (
  SELECT DISTINCT
    s.REP_LDAP,
    s.MERCHANT_TOKEN,
    CASE WHEN s.IS_FNB = 1 THEN 1 ELSE 3 END AS SIGN_PTS,
    CASE WHEN a.IS_FNB = 1 THEN 1 ELSE 3 END AS ACT_PTS
  FROM signs s
  JOIN activations a ON s.MERCHANT_TOKEN = a.MERCHANT_TOKEN AND s.REP_LDAP = a.REP_LDAP
  WHERE s.OPPORTUNITY_AMOUNT_LOCAL >= 250000
),
rep_signs AS (
  SELECT REP_LDAP, REP_NAME,
    SUM(CASE WHEN IS_FNB = 1 THEN 1 ELSE 3 END) AS SIGN_POINTS,
    COUNT(*) AS SIGN_COUNT
  FROM signs GROUP BY REP_LDAP, REP_NAME
),
rep_acts AS (
  SELECT REP_LDAP, REP_NAME,
    SUM(CASE WHEN IS_FNB = 1 THEN 1 ELSE 3 END) AS ACT_POINTS,
    COUNT(*) AS ACT_COUNT
  FROM activations GROUP BY REP_LDAP, REP_NAME
),
rep_loans AS (
  SELECT REP_LDAP, REP_NAME,
    SUM(LOAN_POINTS) AS LOAN_POINTS,
    COUNT(*) AS LOAN_COUNT
  FROM loans GROUP BY REP_LDAP, REP_NAME
),
rep_double AS (
  SELECT REP_LDAP,
    SUM(SIGN_PTS + ACT_PTS) AS DOUBLE_BONUS_POINTS,
    COUNT(*) AS DOUBLE_COUNT
  FROM double_bonus GROUP BY REP_LDAP
),
combined AS (
  SELECT 
    COALESCE(s.REP_LDAP, a.REP_LDAP, l.REP_LDAP) AS REP_LDAP,
    COALESCE(s.REP_NAME, a.REP_NAME, l.REP_NAME) AS REP_NAME,
    COALESCE(s.SIGN_POINTS, 0) AS SIGN_POINTS,
    COALESCE(s.SIGN_COUNT, 0) AS SIGN_COUNT,
    COALESCE(a.ACT_POINTS, 0) AS ACT_POINTS,
    COALESCE(a.ACT_COUNT, 0) AS ACT_COUNT,
    COALESCE(l.LOAN_POINTS, 0) AS LOAN_POINTS,
    COALESCE(l.LOAN_COUNT, 0) AS LOAN_COUNT,
    COALESCE(d.DOUBLE_BONUS_POINTS, 0) AS DOUBLE_BONUS_POINTS,
    COALESCE(d.DOUBLE_COUNT, 0) AS DOUBLE_COUNT
  FROM rep_signs s
  FULL OUTER JOIN rep_acts a ON s.REP_LDAP = a.REP_LDAP
  FULL OUTER JOIN rep_loans l ON COALESCE(s.REP_LDAP, a.REP_LDAP) = l.REP_LDAP
  LEFT JOIN rep_double d ON COALESCE(s.REP_LDAP, a.REP_LDAP, l.REP_LDAP) = d.REP_LDAP
)
SELECT 
  c.REP_LDAP,
  c.REP_NAME,
  e.DIRECT_LEAD AS MANAGER,
  CASE 
    WHEN e.DIRECT_LEAD IN ('Steve McMahon','Jonathan DeJesus','Zachary Farley','Dan Cook','Kristin Moore','Meghan McFarlane','Chris Moran','Sean Avery') THEN 'East'
    WHEN e.DIRECT_LEAD IN ('Phillip Skillern','Ramon Quevedo','Alessandra Verne','Scott Hockaday','Matthew Vitale','Stephen Stinchcomb') THEN 'Central'
    WHEN e.DIRECT_LEAD IN ('Nate Obermark','Colter Wilson','Bryan Carter','Brett Rousse','Jonathan Sheridan','Alison Rushworth','Gareth James') THEN 'West'
    ELSE e.REGION
  END AS REGION,
  c.SIGN_POINTS,
  c.SIGN_COUNT,
  c.ACT_POINTS,
  c.ACT_COUNT,
  c.LOAN_POINTS,
  c.LOAN_COUNT,
  c.DOUBLE_BONUS_POINTS,
  c.DOUBLE_COUNT,
  (c.SIGN_POINTS + c.ACT_POINTS + c.LOAN_POINTS + c.DOUBLE_BONUS_POINTS) AS TOTAL_POINTS
FROM combined c
JOIN APP_SALES.APP_SALES_ETL.FACT_FIELD_SALES_EMPLOYMENT_CURRENT e ON c.REP_LDAP = e.LDAP
WHERE e.SALES_TEAM = 'Sales - US Field' AND e.ACTIVE_STATUS = 'Active'
ORDER BY TOTAL_POINTS DESC;
